name: epub
version: 2.0.2
author: Colin Nelson <colinnlsn@gmail.com>
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter 
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.0.0-dev.61.0 <3.0.0"
dependencies:
  async: "^2.1.0"
  archive: "^3.1.2"
  quiver: '>=2.0.0 <=3.0.1'
  xml: ">=2.6.0 <=5.1.0 "
  image: ">=1.1.33 <=3.0.2"
  dart2_constant: ^1.0.1
  path: "^1.8.0"
dev_dependencies:
  test: "^1.5.1"
  #path: "^1.5.1"
